import { useState, useEffect, type FormEvent } from 'react';
import { ScanLine, Snowflake, Boxes, Sprout, Truck, Layers, Check, Menu, X, WifiOff, ClipboardCheck } from 'lucide-react';
const stages = [
 {name:'Cosecha',icon:Sprout,title:'El control empieza en el campo.',body:'Identificá cada BIN y vinculalo con su productor, origen y variedad. La información acompaña a la fruta desde el primer registro.',label:'BIN identificado',code:'BIN · 00428',detail:'Granada · Wonderful',rows:[['Origen','Cuadro 02'],['Estado','Listo para consolidar'],['Registro','Cosecha']]},
 {name:'Recepción',icon:ScanLine,title:'Cada ingreso, con su información.',body:'Consolidá los BINs en un lote, registrá transporte y pesado, y confirmá la llegada a playa de empaque.',label:'Recepción confirmada',code:'LOTE · 00136',detail:'8 BINs vinculados',rows:[['Pesado','Registrado'],['Destino','Playa de empaque'],['Registro','Recepción']]},
 {name:'Producción',icon:Layers,title:'De la materia prima al pallet.',body:'Registrá el vuelco por QR y seguí la producción y los pallets. Conservá los vínculos disponibles para consultar su recorrido.',label:'Pallet registrado',code:'PALLET · 00214',detail:'Producto fresco',rows:[['Peso neto','480 kg'],['Bultos','120 cajas'],['Registro','Producción']]},
 {name:'Prefrío',icon:Snowflake,title:'Posiciones claras. Ciclos controlados.',body:'Asigná la primera posición libre y seguí el ciclo de prefrío. Durante el proceso, el túnel queda bloqueado para mantener sus pallets juntos.',label:'Ciclo en proceso',code:'TÚNEL · 03',detail:'Posición 06 de 18',rows:[['Ingreso','Registrado'],['Ciclo','En proceso'],['Movimientos','Bloqueados hasta finalizar']]},
 {name:'Cámaras',icon:Boxes,title:'El stock tiene un lugar.',body:'Ubicá pallets por cámara, carga y posición. Consultá ocupación y permanencia, con cargas flexibles según la distribución física.',label:'Ubicación confirmada',code:'CÁMARA · 02',detail:'Carga 03 · Posición 12',rows:[['Pallet','PAL · 00214'],['Capacidad de carga','20 o 21 pallets'],['Registro','Almacenamiento']]},
 {name:'Despacho',icon:Truck,title:'Una salida que cierra el recorrido.',body:'Armá el despacho, vinculá sus pallets y confirmá la salida. Consultá qué se envió y el historial registrado de cada unidad.',label:'Carga preparada',code:'DESPACHO · 00018',detail:'20 pallets asociados',rows:[['Estado','Listo para despachar'],['Salida','Pendiente de confirmación'],['Registro','Despacho']]}
];
function Brand({light=false}:{light?:boolean}) {return <a href="#inicio" className={`brand ${light?'light':''}`} aria-label="Empaco, inicio"><span className="brand-mark" aria-hidden="true">e</span><span>empaco<span className="brand-period">.</span></span></a>}
export default function Home(){
 const [menu,setMenu]=useState(false),[active,setActive]=useState(0),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false),[requestId,setRequestId]=useState('');
 const stage=stages[active]; const Icon=stage.icon;
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool={name:'show_operation_stage',title:'Explorar una etapa de Empaco',description:'Muestra en la página la etapa seleccionada del recorrido. No registra operaciones ni envía solicitudes.',inputSchema:{type:'object',properties:{stage:{type:'string',enum:stages.map(s=>s.name)}},required:['stage'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Indicá una etapa válida.');const name=(input as {stage?:unknown}).stage;const i=stages.findIndex(s=>s.name===name);if(i<0)throw Error('Etapa no válida.');setActive(i);document.getElementById('recorrido')?.scrollIntoView({behavior:'smooth'});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {stage:stages[i].name,title:stages[i].title};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setStatus('');const fd=new FormData(form);const id=requestId||crypto.randomUUID();setRequestId(id);try{const r=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name:fd.get('name'),email:fd.get('email'),company:fd.get('company'),crop:fd.get('crop'),message:fd.get('message'),website:fd.get('website'),consent:fd.get('consent')==='on'})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'No pudimos registrar tu solicitud. Intentá nuevamente.');setSuccess(true);setStatus('Tu solicitud quedó registrada. Gracias por contarnos sobre tu operación.');}catch(err){setStatus(err instanceof Error?err.message:'No pudimos conectar. Conservamos tus datos para que puedas volver a intentar.');}finally{setBusy(false);}}
 return <><a className="skip-link" href="#contenido">Saltar al contenido</a>
 <header className="site-header" id="inicio"><div className="container nav"><Brand/><nav aria-label="Navegación principal" className={menu?'nav-links expanded':'nav-links'}><a href="#tecnologia" onClick={()=>setMenu(false)}>Tecnología</a><a href="#recorrido" onClick={()=>setMenu(false)}>Trazabilidad</a><a href="https://app.empaco.com.ar/login">Ingresar a la app</a></nav><a className="button dark header-cta" href="#demo"><span className="cta-long">Solicitar una demo</span><span className="cta-short">Demo</span></a><button className="menu-toggle" aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="contenido"><section className="hero container"><div className="hero-copy"><p className="eyebrow">Tecnología para cosecha y empaque</p><h1>Cada lote.<br/>Cada movimiento.<br/><em>Todo conectado.</em></h1><p className="hero-description">Digitalizá tu operación y seguí el recorrido de la fruta: origen, producción, frío y despacho. Información conectada, trazabilidad al alcance de tu equipo.</p><div className="hero-buttons"><a className="button dark" href="#demo">Solicitar una demo</a><a className="text-link" href="#recorrido">Ver cómo funciona</a></div><p className="hero-note"><ScanLine size={16}/> QR <span>·</span> iOS, Android y Web</p></div>
 <div className="trace-preview" aria-label="Ejemplo ilustrativo del seguimiento de un pallet"><div className="trace-preview-header"><span><ScanLine size={17}/> Trazabilidad</span><span>Ejemplo ilustrativo</span></div><div className="trace-photo"><img src="/commercial-harvest.jpg" alt="Granadas recién cosechadas en un cajón" width="1536" height="1024" fetchPriority="high"/><span>Un origen. Un recorrido.</span></div><div className="trace-preview-body"><p className="small-label">Unidad identificada</p><div className="trace-unit"><h2>PAL · 00214</h2><span>Producto fresco</span></div><div className="trace-flow"><div><span className="trace-step"><Sprout size={17}/></span><div><strong>Origen registrado</strong><p>Cuadro 02 · Wonderful</p></div><Check size={17}/></div><div><span className="trace-step"><ScanLine size={17}/></span><div><strong>Lote vinculado</strong><p>LOTE · 00136</p></div><Check size={17}/></div><div><span className="trace-step"><Snowflake size={17}/></span><div><strong>Ubicación confirmada</strong><p>Cámara 02 · Carga 03 · Posición 12</p></div><Check size={17}/></div></div><div className="trace-summary"><ClipboardCheck size={16}/> Consultá los movimientos registrados.</div></div></div></section>
 <section id="tecnologia" className="technology container" aria-label="Tecnología de Empaco"><article><ScanLine/><div><h2>Identificación por QR</h2><p>Registrá BINs, lotes y pallets desde el celular.</p></div></article><article><ClipboardCheck/><div><h2>Información centralizada</h2><p>Equipos conectados, con permisos por función.</p></div></article><article><WifiOff/><div><h2>Sincronización al reconectar</h2><p>Los movimientos compatibles quedan pendientes hasta validarse.</p></div></article></section>
 <section id="recorrido" className="journey-section"><div className="container"><div className="section-top"><div><p className="eyebrow">Trazabilidad operativa</p><h2>Del campo al despacho.<br/><em>Sin perder el hilo.</em></h2></div><p className="section-intro">Identificá cada unidad, vinculá sus registros y consultá qué pasó en cada etapa.</p></div><div className="stage-tabs" role="tablist" aria-label="Etapas de la operación">{stages.map((s,i)=><button key={s.name} role="tab" id={`tab-${i}`} aria-selected={active===i} aria-controls="stage-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?5:(i+(e.key==='ArrowRight'?1:5))%6;setActive(n);document.getElementById(`tab-${n}`)?.focus();}}}><span>0{i+1}</span>{s.name}</button>)}</div><div className="stage-panel" role="tabpanel" id="stage-panel" aria-labelledby={`tab-${active}`}><div className="stage-copy"><Icon size={27}/><h3>{stage.title}</h3><p>{stage.body}</p></div><div className="operation-preview"><div className="preview-header"><span className="preview-brand">empaco.</span><span>Ejemplo ilustrativo</span></div><div className="preview-body"><div className="preview-state"><Check size={15}/>{stage.label}</div><h4>{stage.code}</h4><p>{stage.detail}</p><dl>{stage.rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div></div></div></div></section>
 <section id="demo" className="demo-section"><div className="container demo-grid"><div className="demo-copy"><p className="eyebrow">Conocé Empaco</p><h2>Conectemos<br/><em>tu operación.</em></h2><p>Veamos cómo aplicar tecnología y trazabilidad a tu cosecha y empaque.</p><span className="demo-note">Una demostración enfocada en tu proceso.</span></div><div className="demo-form-wrap">{success?<div className="form-success" role="status"><Check size={36}/><h3>Solicitud registrada.</h3><p>{status}</p><button className="button dark" onClick={()=>{setSuccess(false);setStatus('');setRequestId('');}}>Enviar otra consulta</button></div>:<form onSubmit={submit}><h3>Solicitá una demo</h3><div className="form-grid"><label>Tu nombre<input name="name" autoComplete="name" required maxLength={100} placeholder="Nombre y apellido"/></label><label>Empresa<input name="company" autoComplete="organization" required maxLength={150} placeholder="Tu establecimiento"/></label></div><label>Correo electrónico<input type="email" name="email" autoComplete="email" required maxLength={254} placeholder="nombre@empresa.com"/></label><label>¿Qué necesitás resolver? <span className="optional">(opcional)</span><textarea name="message" maxLength={2000} rows={2} placeholder="Contanos brevemente sobre tu operación"/></label><label className="honeypot" aria-hidden="true">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input name="consent" type="checkbox" required/><span>Acepto que usen estos datos para responder mi consulta.</span></label>{status&&<p className="form-error" role="alert">{status}</p>}<button className="button dark submit-button" disabled={busy}>{busy?'Registrando…':'Solicitar una demo'}</button><p className="form-note">Sin compromiso.</p></form>}</div></div></section>
 </main><footer className="footer"><div className="container footer-inner"><div><Brand light/><p>Tecnología y trazabilidad para tu empaque.</p></div><div className="footer-links"><a href="/commercial-logo.svg" download>Descargar logo</a><span>© {new Date().getFullYear()} Empaco</span></div></div></footer></>;
}

