-- Synthetic records are rolled back; exercise actual authenticated RPCs.
begin;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='admin' order by id limit 1),true);
set local role authenticated;
do $$
declare
  a text:=gen_random_uuid()::text; b text:=gen_random_uuid()::text;
  lot text:=gen_random_uuid()::text; other_lot text:=gen_random_uuid()::text;
  code_a text:='BIN-TEST-'||a; code_b text:='BIN-TEST-'||b;
  harvest_id uuid:=gen_random_uuid(); dump_id uuid:=gen_random_uuid();
  payload jsonb; result jsonb; state jsonb; n integer; failed boolean;
begin
  payload:=jsonb_build_object('bin_code',code_a,'producer','LAS 500','variety','Wonderful','origin','OP1NE','crew','A','harvest_date','2026-09-30');
  result:=public.harvest_bin_operation(harvest_id,a,payload);
  if result->'bin' ? 'receipt_lot_id' or result->'bin' ? 'net_weight' or result->'bin' ? 'transport' then raise exception 'Cosecha contains lot, weight or transport'; end if;
  result:=public.harvest_bin_operation(harvest_id,a,payload);
  if result->>'already_applied'<>'true' then raise exception 'Harvest replay duplicated data'; end if;
  failed:=false;
  begin perform public.harvest_bin_operation(gen_random_uuid(),gen_random_uuid()::text,payload);
  exception when others then failed:=true; end;
  if not failed then raise exception 'Duplicate harvest QR accepted'; end if;
  perform public.harvest_bin_operation(gen_random_uuid(),b,jsonb_build_object('bin_code',code_b,'producer','GLONET','variety','Wonderful','origin','CUADRO 1','crew','B','harvest_date','2026-09-30'));
  failed:=false;
  begin perform public.patch_record('Bin',a,jsonb_build_object('producer','Changed'));
  exception when others then failed:=true; end;
  if not failed then raise exception 'Generic patch modified harvest'; end if;
  failed:=false;
  begin perform public.field_lot_operation(gen_random_uuid(),lot,'create',jsonb_build_object('workflow_version',3,'lot_code','LOT-TEST-'||lot));
  exception when others then failed:=true; end;
  if not failed then raise exception 'Consolidation allowed no transport'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'create',jsonb_build_object('workflow_version',3,'lot_code','LOT-TEST-'||lot,'transport','Camión A'));
  perform public.field_lot_operation(gen_random_uuid(),other_lot,'create',jsonb_build_object('workflow_version',3,'lot_code','LOT-TEST-'||other_lot,'transport','Camión B'));
  failed:=false;
  begin perform public.field_lot_operation(gen_random_uuid(),lot,'close');
  exception when others then failed:=true; end;
  if not failed then raise exception 'Empty consolidation closed'; end if;
  failed:=false;
  begin perform public.field_lot_operation(gen_random_uuid(),lot,'add_bin','{}','BIN-UNKNOWN-'||lot);
  exception when others then failed:=true; end;
  if not failed then raise exception 'Unknown BIN accepted'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'add_bin','{}',code_a);
  failed:=false;
  begin perform public.field_lot_operation(gen_random_uuid(),other_lot,'add_bin','{}',code_a);
  exception when others then failed:=true; end;
  if not failed then raise exception 'BIN belongs to two lots'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'remove_bin','{}',code_a);
  select data into state from public.records where entity='Bin' and id=a;
  if state ? 'receipt_lot_id' or state->>'origin'<>'OP1NE' or state->>'status'<>'cosechado' then raise exception 'Removal lost harvest metadata'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'add_bin','{}',code_a);
  perform public.field_lot_operation(gen_random_uuid(),lot,'add_bin','{}',code_b);
  perform public.field_lot_operation(gen_random_uuid(),lot,'close');
  failed:=false;
  begin perform public.field_lot_operation(gen_random_uuid(),lot,'remove_bin','{}',code_a);
  exception when others then failed:=true; end;
  if not failed then raise exception 'Closed lot changed'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'weigh','{}',null,1300.1,300);
  select count(*) into n from public.records where entity='Bin' and data->>'receipt_lot_id'=lot and abs((data->>'net_weight')::numeric-500.05)<0.0000001;
  if n<>2 then raise exception 'Prorated weight incorrect'; end if;
  select data into state from public.records where entity='Bin' and id=a;
  if state->>'origin'<>'OP1NE' or state->>'crew'<>'A' then raise exception 'Weight overwrote bin harvest'; end if;
  select data into state from public.records where entity='ReceiptLot' and id=lot;
  if state->>'transport'<>'Camión A' or state->>'producer'<>'GLONET / LAS 500' then raise exception 'Lot summary incorrect'; end if;
  failed:=false;
  begin perform public.dump_bin_by_qr(gen_random_uuid(),a,lot,code_a,'VOL-TEST');
  exception when others then failed:=true; end;
  if not failed then raise exception 'Dump allowed before yard receipt'; end if;
  perform public.field_lot_operation(gen_random_uuid(),lot,'receive');
  failed:=false;
  begin perform public.dump_lot_by_bins(gen_random_uuid(),lot,1,'VOL-TEST-COUNT');
  exception when others then failed:=true; end;
  if not failed then raise exception 'Harvest lot allowed anonymous count-based dump'; end if;
  failed:=false;
  begin perform public.dump_bin_by_qr(gen_random_uuid(),a,other_lot,code_a,'VOL-WRONG');
  exception when others then failed:=true; end;
  if not failed then raise exception 'BIN deducted from wrong lot'; end if;
  perform public.dump_bin_by_qr(dump_id,a,lot,code_a,'VOL-TEST');
  perform public.dump_bin_by_qr(dump_id,a,lot,code_a,'VOL-TEST');
  failed:=false;
  begin perform public.dump_bin_by_qr(gen_random_uuid(),a,lot,code_a,'VOL-DUPLICATE');
  exception when others then failed:=true; end;
  if not failed then raise exception 'Same BIN consumed twice'; end if;
  select data into state from public.records where entity='Bin' and id=a;
  if state->>'status'<>'volcado' or state->>'dumped_at' is null or state->>'origin'<>'OP1NE' or state->>'receipt_lot_id'<>lot then raise exception 'BIN dump lost traceability'; end if;
  perform public.dump_bin_by_qr(gen_random_uuid(),b,lot,code_b,'VOL-TEST-FINAL');
  select data into state from public.records where entity='ReceiptLot' and id=lot;
  if (state->>'remaining_weight')::numeric<>0 or (state->>'dumped_weight')::numeric<>1000.1 or (state->>'bins_dumped')::integer<>2 then raise exception 'Dump balances incorrect'; end if;
  perform public.harvest_bin_operation(gen_random_uuid(),gen_random_uuid()::text,payload);
  select count(*) into n from public.records where entity='Bin' and data->>'bin_code'=upper(code_a);
  if n<>2 then raise exception 'QR reuse lost history'; end if;
  result:=public.harvest_bin_operation(harvest_id,a,payload);
  if result->>'already_applied'<>'true' then raise exception 'Late harvest replay failed'; end if;
end;
$$;
rollback;
select 'PASS: cosecha individual, QR único, consolidación, transporte, ficha preservada, pesado, playa, vuelco e historial; sin datos de prueba persistidos' as verification;
